### ISSUE TITLE
Text rendering is blurry in the Gaussian splat scene.

### ISSUE THREAD

**Issue by cloris** [sparkjsdev/spark#248]
I used Spark to render a PLY and found that the text in the scene is very blurry, but it appears very clear in MKK — could you please take a look?

In Spark:
<img width="503" height="288" alt="Image" src="https://github.com/user-attachments/assets/9c40b496-957c-4f3c-9eee-e71c83a1140a" />

In Mkk:
<img width="545" height="325" alt="Image" src="https://github.com/user-attachments/assets/0a7b8fab-dc55-4225-a078-35384a9f07d9" />

Ply file:
https://1drv.ms/u/c/1ad718b987e56d68/IQDA0kmJX3JTR6-RGrccw-iPAbCoYeco6MTtinhMNIxdDMs?e=l3Kgo5

Code:
`import "./style.css";
import * as THREE from "three";
import { SparkRenderer, SplatMesh } from "@sparkjsdev/spark";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import Stats from "three/examples/jsm/libs/stats.module.js";
const stats = new Stats();
document.body.appendChild(stats.dom);
let titleDiv = document.createElement("div");
titleDiv.id = "apptitle";
titleDiv.textContent = "spark";
document.body.appendChild(titleDiv);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
  60,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);
camera.up.set(0, 0, 1);
const renderer = new THREE.WebGLRenderer({ antialias: true,  precision: 'highp' });
renderer.setPixelRatio(window.devicePixelRatio || 1);
renderer.setSize(window.innerWidth, window.innerHeight);
document
  .querySelector<HTMLDivElement>("#app")!
  .appendChild(renderer.domElement);

const splatURL = "point_cloud.ply";
const splatMesh = new SplatMesh({ url: splatURL });
scene.add(splatMesh);

const controls = new OrbitControls(camera, renderer.domElement);
controls.object.position.set(60.28,-24.62,1)
controls.target.set(60.28,-25.62,1);

renderer.setAnimationLoop(function animate(time) {
  stats.update()  // 更新FPS显示
  controls.update(time);
  renderer.render(scene, camera);
});

window.addEventListener("resize", () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  // set pixel ratio before size so the backing store is correct
  renderer.setPixelRatio(window.devicePixelRatio || 1);
  renderer.setSize(window.innerWidth, window.innerHeight);
});
`

**Comment by mrxz** [comment]
The splats in your .ply file are quite far away from the origin. Internally spark uses float16 values for the splat centers. What you're seeing are quantization artifacts. It's recommended to try and keep your splats near the origin, both in the source file(s) as well as in your scene.

To minimize the quantization artifacts you can recenter the splats in your file, [attach the camera to the `SparkRenderer`](https://sparkjs.dev/docs/spark-renderer/#larger-scenes) and translate the `SplatMesh` to the desired location.

The upcoming LOD feature does introduce an extended splat representation that is no longer limited to float16. That would also resolve this issue without any workarounds.

**Comment by cloris** [comment]
@mrxz Thank you for explaining. We're excited about Spark's upcoming LOD implementation

**Comment by dmarcos** [comment]
> [@mrxz](https://github.com/mrxz) Thank you for explaining. We're excited about Spark's upcoming LOD implementation

Did you try attaching the camera to the SparkRenderer and translated the SplatMesh as suggested?

**Comment by BordeauxWind** [comment]
@dmarcos I also encountered the same problem. However, using the above method did not solve the issue of artifacts. This is because the range of the file I loaded was very large. The rendering near the origin was normal, but when it was far from the origin, rendering artifacts would occur. The model's dimensions are 820m by 500m. The artifacts at the edges of the model are particularly severe. Are there any other solutions? For example, could we abandon float16 and use float32 instead?

**Comment by cloris** [comment]
> > [@mrxz](https://github.com/mrxz) Thank you for explaining. We're excited about Spark's upcoming LOD implementation
> 
> Did you try attaching the camera to the SparkRenderer and translated the SplatMesh as suggested?

@dmarcos  I have atteched the camera to the SparkRender and translated the Splash, but didn't solve the issue.

`import "./style.css";
import * as THREE from "three";
import { SparkRenderer, SplatMesh } from "@sparkjsdev/spark";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import Stats from "three/examples/jsm/libs/stats.module.js";
const stats = new Stats();
document.body.appendChild(stats.dom);
let titleDiv = document.createElement("div");
titleDiv.id = "apptitle";
titleDiv.textContent = "spark";
document.body.appendChild(titleDiv);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
60,
window.innerWidth / window.innerHeight,
0.1,
1000
);
camera.up.set(0, 0, 1);
const renderer = new THREE.WebGLRenderer({ antialias: true, precision: 'highp' });
renderer.setPixelRatio(window.devicePixelRatio || 1);
renderer.setSize(window.innerWidth, window.innerHeight);
document
.querySelector("#app")!
.appendChild(renderer.domElement);

const splatURL = "point_cloud.ply";
const splatMesh = new SplatMesh({ url: splatURL });
splatMesh.position.set(-60.28, 25.62, -1);
scene.add(splatMesh);

const sparkRenerer = new SparkRenderer({
  renderer: renderer,
});
scene.add(sparkRenerer);
camera.add(sparkRenerer);

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0, 0);
controls.object.position.set(0,1,0);
controls.update();

renderer.setAnimationLoop(function animate(time) {
stats.update()
controls.update(time);
renderer.render(scene, camera);
});

window.addEventListener("resize", () => {
camera.aspect = window.innerWidth / window.innerHeight;
camera.updateProjectionMatrix();
renderer.setPixelRatio(window.devicePixelRatio || 1);
renderer.setSize(window.innerWidth, window.innerHeight);
});`

**Comment by mrxz** [comment]
@cloris In Three.js, an object can only have a single parent. The following part of your snippet isn't quite correct:
```js
const sparkRenerer = new SparkRenderer({
    renderer: renderer,
});
scene.add(sparkRenerer);
camera.add(sparkRenerer);
```

At the end the `SparkRenderer` _is_ added to the camera, but not to the scene. You'll have to add the camera to the scene as well, as shown in the documentation: https://sparkjs.dev/docs/spark-renderer/#larger-scenes. Going by your code snippet, the following change should be made:
```diff
const sparkRenerer = new SparkRenderer({
    renderer: renderer,
});
-scene.add(sparkRenerer);
+scene.add(camera);
camera.add(sparkRenerer);
```

**Comment by cloris** [comment]
@mrxz I really appreciate you taking the time to review the code and provide feedback. I've applied the modifications you suggested. However, the text still appears blurry. Could we take another look together to see if we're missing something else?
`
import "./style.css";
import * as THREE from "three";
import { SparkRenderer, SplatMesh } from "@sparkjsdev/spark";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import Stats from "three/examples/jsm/libs/stats.module.js";
const stats = new Stats();
document.body.appendChild(stats.dom);
let titleDiv = document.createElement("div");
titleDiv.id = "apptitle";
titleDiv.textContent = "spark";
document.body.appendChild(titleDiv);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
60,
window.innerWidth / window.innerHeight,
0.1,
1000
);
camera.up.set(0, 0, 1);
const renderer = new THREE.WebGLRenderer({ antialias: true, precision: 'highp' });
renderer.setPixelRatio(window.devicePixelRatio || 1);
renderer.setSize(window.innerWidth, window.innerHeight);
document
.querySelector("#app")!
.appendChild(renderer.domElement);

const splatURL = "point_cloud.ply";
const splatMesh = new SplatMesh({ url: splatURL });
splatMesh.position.set(-60.28, 25.62, -1);
scene.add(splatMesh);

**const sparkRenerer = new SparkRenderer({
  renderer: renderer,
});
scene.add(camera);
camera.add(sparkRenerer);**

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0, 0);
controls.object.position.set(0,1,0);
controls.update();

const axesHelper = new THREE.AxesHelper(200);
scene.add(axesHelper);

renderer.setAnimationLoop(function animate(time) {
stats.update();
controls.update(time);
renderer.render(scene, camera);
});

window.addEventListener("resize", () => {
camera.aspect = window.innerWidth / window.innerHeight;
camera.updateProjectionMatrix();
renderer.setPixelRatio(window.devicePixelRatio || 1);
renderer.setSize(window.innerWidth, window.innerHeight);
});
`

**Comment by mrxz** [comment]
@cloris To minimize the quantization errors, two conditions must be met:

- The splats must be close/near the origin _in the source file_
- The `SplatMesh` must be close/near the origin of the `SparkRenderer` (hence adding it to the camera)

The second condition should be fine given the updated code snippet. To verify the first one, you can load the .ply file in either the [Spark Viewer](https://sparkjs.dev/viewer/) or the [SuperSplat Editor](https://superspl.at/editor) and make sure the splats show up at the origin. If not, you can use a tool like [splat-transform](https://github.com/playcanvas/splat-transform) to move them to the origin. Afterwards verify that the updated splat file still renders fine.

If the issue still persists after this, a full runnable example with the (updated) .ply file would help with debugging. At the very least make sure you're using the latest release of Spark.

> ```js
> const renderer = new THREE.WebGLRenderer({ antialias: true, precision: 'highp' });
> ```

I assume you've enabled antialiasing in an attempt to fix the blurry nature, but it's worth pointing out that you generally should [disable antialiasing](https://sparkjs.dev/docs/performance/#threewebglrendererantialias) when rendering splats. This won't affect visuals, but will have a noticeable effect on performance.

**Comment by cloris** [comment]
@mrxz I implemented first condition and the issue has been resolved. Thank you very much for your patience throughout the process. I'm also very much looking forward to the LOD release.

**Comment by fuxy-clude** [comment]
@cloris 你好能详细介绍一下怎样调整splats 靠近原点吗？ 我也遇到了这个问题 尝试使用[supersplat.at](https://superspl.at/editor)将中心调整到0,0,0 发现文字清晰度还是与playcanvas有较大差距

**Comment by phoenixbf** [comment]
Hi all!
I also have this problem and found this issue. In my case there is just one single GS loaded in the scene.

Having SparkRenderer as child of camera does not seem to solve artifacts in my case. This location here is also not too far from absolute origin (around 30m)

<img width="1020" height="891" alt="Image" src="https://github.com/user-attachments/assets/11af5ac2-e928-4628-90ca-34a24705886d" />

Am I missing something?

**Comment by xiemeilong** [comment]
@mrxz This issue still exists. I tested it on: https://sparkjs.dev/2.0.0-preview/viewer

**Comment by mrxz** [comment]
@xiemeilong To make use of the extended splat representation, you need to enable it when loading your splat files. See the `extSplats` property for `SplatMesh`: https://sparkjs.dev/2.0.0-preview/docs/splat-mesh/#optional-parameters

```js
const splatMesh = new SplatMesh({ ..., extSplats: true });
```
